### PR TITLE
Added a search page

### PR DESCRIPTION
**Pull request by Acel-01**
PR for issue #263

### CODE REVIEW

**Comment by EphraimDev** [comment]
add pictures for web and mobile view

**Comment by Acel-01** [comment]
Which pictures sir?
I didn't see any pictures on the design 

Please explain what you mean

**Comment by EphraimDev** [comment]
Picture of how it looks on your local

According to design, when the search icon is clicked on the navbar, it is supposed to open a search box below. Did you see that on the design?

**Comment by Acel-01** [comment]
Mobile view 
FG Expense - Search (2)

Web view
FG Expense - Search (3)

**Comment by Acel-01** [comment]
@EphraimDev I've updated my fork
you can merge now

**Pull request merged**
