### PR TITLE
 quarterly parsing done

### PR DESCRIPTION
**Pull request by onifs10**

### CODE REVIEW

**Comment by onifs10** [comment]
`php artisan migrate:fresh --seed`
`php artisan parse:quarterly`

**Comment by EphraimDev** [comment]
@onifs10 are we refreshing the database because of that one change to that table of its more than that? If we refresh the db, then we have to scrape the site again, parse all sheets again. Is this necessary? If all this is just to parse the quarterly sheets, then there's another way

**Comment by onifs10** [comment]
there is really no need to refresh ... you can just add a column to the quarterly budget table in the databse

**Comment by onifs10** [comment]
name of column is categories varchar 255 @EphraimDev

**Comment by EphraimDev** [comment]
If that's the case, create a new migration file that will add the changes to the same table so that when migration is run, it just runs only the newly added files instead of a fresh migration

**Comment by onifs10** [comment]
aiit sir

**Comment by onifs10** [comment]
done @EphraimDev

**Pull request merged**
