### PR TITLE
Complete admin dashboard

### PR DESCRIPTION
**Pull request by Ezeko**

### CODE REVIEW

**Review by goodhands — CHANGES_REQUESTED** [review]
This is what I see on the login page:
image

And after registration & login, it redirects me to `/home` which returned 404 not found.

And after I eventually found my way to the dashboard, I see this:
image

We have to remove the white colours from the sidebar

**Comment by Ezeko** [comment]
I have initially checked that both the updates returned back to initial state. I will change the home service provider

**Comment by Ezeko** [comment]
Route service provider updated

**Comment by Ezeko** [comment]
@goodhands You need to run npm run dev after npm install and composer update

**Pull request closed without merging**
