### PR TITLE
our_team_page_complete

### PR DESCRIPTION
**Pull request by sylvercodez**
our team page is complete

### CODE REVIEW

**Comment by EphraimDev** [comment]
To render each member, do it in a way that if I don't provide my Facebook name, the Facebook icon won't be visible. This is to avoid dead links. 

And why did you remove email?

**Comment by sylvercodez** [comment]
email was not in the design and frontend

**Comment by EphraimDev** [comment]
Add it please

**Comment by sylvercodez** [comment]
pls what will the route be in href

**Comment by EphraimDev** [comment]
Use the mailto attribute in links

**Pull request merged**
