### PR TITLE
minister profile page

### PR DESCRIPTION
**Pull request by Ezeko**
Make ministry_profile blade
make it show with showProfile function
create ministry_profile.css
Screenshot (68)

### CODE REVIEW

**Comment by goodhands** [comment]
Hey boss, please try to make the page reflect the figma design as much as possible:

Ministry profile

**Comment by goodhands** [comment]
Also we have to use a graph to replace those images

**Comment by Ezeko** [comment]
Screenshot (70)
Screenshot (71)

**Comment by Ezeko** [comment]
Screenshot (73)

**Comment by Ezeko** [comment]
Screenshot (75)

**Pull request merged**
