### PR TITLE
Feedback Engine Updated 

### PR DESCRIPTION
**Pull request by pepps01**
The above is fully built
- The Admin displays 
- The homepage displays the modal Form
- Notification is still in progress
- Actions to Ignore and approve has been added.

On both FrontEnd and BackEnd

### CODE REVIEW

**Comment by goodhands** [comment]
Conflicts

**Comment by pepps01** [comment]
Hi Samuel, 
Please give me write access to resolve it.

**Comment by goodhands** [comment]
You should resolve it locally

**Comment by goodhands** [comment]
Directions: 
image

**Comment by pepps01** [comment]
Thank you

**Comment by pepps01** [comment]
I have made the changes as instructed above.

**Pull request closed without merging**
