### PR TITLE
admin_dashboard fixed 

### PR DESCRIPTION
**Pull request by onifs10**

### CODE REVIEW

**Review by EphraimDev — COMMENTED** [review]
Why are we storing tweets in the database?

**Comment by onifs10** [comment]
so the admin can view the tweets ... and delete them if they are not valid

**Comment by onifs10** [comment]
i would schedule a command to empty the tweet_table every month to free space

**Comment by EphraimDev** [comment]
Can't the tweets be pulled directly from the Twitter timeline and displayed on the page instead of storing to db?

**Comment by onifs10** [comment]
it can ...

**Comment by EphraimDev** [comment]
Okay implement  it that way. No need storing to a db

**Comment by EphraimDev** [comment]
Also remove the migration and model files if its still there

**Pull request closed without merging**
