### PR TITLE
Carousel Fix

### PR DESCRIPTION
**Pull request by SkyC0der**
The text now covers the full width of the dark background
wkos
working1

### CODE REVIEW

**Comment by EphraimDev** [comment]
Why do you have changes to the composer.lock file?

**Comment by EphraimDev** [comment]
@SkyC0der why have you not responded to this?

**Comment by SkyC0der** [comment]
Ran "composer update" when I pulled upstream from the test branch

**Comment by SkyC0der** [comment]
I also have changes on the parsesheet.php file because the file had a syntax error that did not let me "serve" my file. I added a temporal fix, @Ezeko will look into the error later

**Comment by EphraimDev** [comment]
Why composer update?

**Comment by EphraimDev** [comment]
Instead of composer install

**Comment by SkyC0der** [comment]
dummy mistake on my end. should I revert the commit

**Comment by SkyC0der** [comment]
Its fixed now

**Pull request merged**
