### PR TITLE
Frontend contractors

### PR DESCRIPTION
**Pull request by AironDev**
I have added extra logic/page to handle certain beneficiaries whose records are not in companies table and finally a fallback to 404 page if for some reasons  matching beneficiary data is equally not found in payments table.

This is an example of a beneficiary whose data is not in companies table

image

### CODE REVIEW

**Comment by goodhands** [comment]
The only beneficiaries we are interested in on this page is "companies". So all contractors are fetched from the companies table, with that it will be impossible to have a company whose record was not found.

**Comment by AironDev** [comment]
I fully understand -
But @EphraimDev wants to test this out as well.

**Comment by AironDev** [comment]
Secondly, the current implementation that is live at test expense and the main server now, does not agree with your assertion.

We have a lot of contractors showing 404, maybe you forgot to change the index method to read from companies table as you mentioned
@goodhands

**Comment by goodhands** [comment]
The only thing I changed so far was making sure the single page for contractors fetches the right contractor from the database. With your new push, you have removed that. Your index method fetches from the payments table to list everyone who has gotten money but when you click on them it says no data found, that is not right and that's because your show method has a bug. I trust you will figure it out as I have to work on something else.

**Pull request merged**
