### PR TITLE
made the view reports and contracts links bolder, changed some footer…

### PR DESCRIPTION
**Pull request by webdott**
fixes in josh's thread

Screenshot from 2020-07-25 20-09-11

Screenshot from 2020-07-25 20-09-23

Screenshot from 2020-07-25 20-34-42

I also added the phone number section to the contact form 

Screenshot from 2020-07-25 21-49-52

### CODE REVIEW

**Comment by EphraimDev** [comment]
Resolve your conflicts please

**Comment by webdott** [comment]
Will do that now sir

**Comment by leeCodes-bit** [comment]
@EphraimDev  chief this what i have been saying, in already fixed this issue, and it has been merged. please this pr shouldnt be merged

**Review by EphraimDev — APPROVED** [review]

**Comment by EphraimDev** [comment]
Is this the changes josh suggested? @leeCodes-bit  @caspero-62

**Comment by webdott** [comment]
Yes sir,

But as for the contact form, I worked on it along side @davidalenoghena

**Comment by EphraimDev** [comment]
Make a pull request and make sure you replace all your changes with the current state. Then push only the files associated with contact form

**Comment by webdott** [comment]
> @EphraimDev chief this what i have been saying, in already fixed this issue, and it has been merged. please this pr shouldnt be merged

Ma calm down. You didn't do the contact form part now
So what's the issue?

**Comment by webdott** [comment]
> Make a pull request and make sure you replace all your changes with the current state. Then push only the files associated with contact form

Okay sir

**Comment by leeCodes-bit** [comment]
@EphraimDev  yes chief. @caspero-62  it is bad practice please and i am calm it is just frustrating

**Comment by webdott** [comment]
> @EphraimDev yes chief. @caspero-62 it is bad practice please and i am calm it is just frustrating

We made this pr around the same time and I just woke up to this. Don't make it seem like I took your work or something

I'll fix the issues as @EphraimDev stated

**Pull request closed without merging**
