### PR TITLE
Comments crud for admin

### PR DESCRIPTION
**Pull request by AironDev**

### CODE REVIEW

**Comment by AironDev** [comment]
image
image
image

**Comment by EphraimDev** [comment]
I don't see the flagged column in the table. Comments can also be flagged or reported

**Comment by AironDev** [comment]
Oops, I missed that - I'll work on it tomorrow.
Please!

**Comment by AironDev** [comment]
image
image
image
image
image

**Comment by AironDev** [comment]
Done, please review

**Pull request merged**
