### PR TITLE
latest expenses for home carousel and bug fix for ministry cards

### PR DESCRIPTION
**Pull request by papa28x4**
Solves issue https://github.com/hngi/expenseng/issues/507

1) Home carousel is now fed with the latest expenses from the payment table
2) fixed bug that doesn't allow the ministry cards to be routed to the profile page on click after a search

### CODE REVIEW

**Comment by EphraimDev** [comment]
Kindly fix your merge conflicts

**Comment by EphraimDev** [comment]
Don't remove some other person's work please

**Comment by papa28x4** [comment]
@EphraimDev I would never do that. At point I made the PR, it read able to merge. It's possible that a pending PR merged before mine triggered the conflict

**Comment by EphraimDev** [comment]
Oh I didn't imply that you would do that o. I stated it so that you'll be extra watchful when resolving the conflicts. I guessed as much that the pr I merged before yours caused it

**Pull request merged**
